tasks:
  - init: go get ./...
    command: go run cmd/nuScrape/nuScrape.go
  - before: sleep 5
    command: gp preview $(gp url 8080)/rest/v1/gesamtspielplan/2021_22/AV/281103

# ports:
#   - port: 8080
#     onOpen: open-preview

vscode:
  extensions:
    - golang.go
