apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationname }}-deployment
  labels:
    app: {{ .Values.applicationname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationname }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationname }}
    spec:
      containers:
        - name: {{ .Values.applicationname }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
