apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuscrape-deployment
  labels:
    app: nuscrape
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nuscrape
  template:
    metadata:
      labels:
        app: nuscrape
    spec:
      containers:
        - name: nuscrape
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
