apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.applicationname }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: k8s-local
      http:
        paths:
          - path: /{{ .Values.applicationname }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.applicationname }}-service
                port:
                  number: 80
